# Generated by Django 4.1.7 on 2023-04-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqzhol', '0002_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='user',
        ),
    ]
