# Generated by Django 4.1.7 on 2023-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqzhol', '0004_statistics_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='second',
            field=models.IntegerField(default=0),
        ),
    ]
